---
users:

  'plone':
    name: 'Plone installation'
    email: 'jon.pentland@pretagov.co.uk'
    public_keys: []
    state: present
    shell: '/bin/bash'
    groups:
      - 'docker'
      - 'plone'
